export default [
    {
        title: "Tom's Midnight Garden",
        author: 'Philippa Pearce',
        society: 'Brighton Little Theatre',
        date: 'Dec 2023',
        roles: ["Operator"],
    },
    {
        title: 'The Tempest',
        author: 'William Shakespeare',
        society: 'Pitch Breath Theatre Company',
        date: 'Nov 2023',
        roles: ["Lighting Operator"],
    },
    {
        title: 'A Spy With A View',
        author: 'Robert Scott',
        society: 'Ifield Barn Theatre (members only)',
        date: 'Jul 2023',
        roles: ["Sound Design", "Stage Manager"],
    },
    {
        title: 'Bonnie & Clyde',
        author: 'Frank Wildhorn',
        society: 'East Surrey Performing Arts',
        date: 'May 2023',
        roles: ["Set Build", "Stagehand"],
    },
    {
        title: 'Ideaphoria',
        author: 'N/A',
        society: 'Leaps and Beats',
        date: 'Apr 2023',
        roles: ["Lighting Design"],
    },
    {
        title: 'Improbable Fiction',
        author: 'Alan Ayckbourn',
        society: 'East Surrey Performing Arts',
        date: 'Feb 2023',
        roles: ["Lighting Design", "Sound Design"],
    },
    {
        title: 'Out of Order',
        author: 'Ray Cooney',
        society: 'East Surrey Performing Arts',
        date: 'Feb 2022',
        roles: ["Lighting Design", "Sound Design"],
    },
]